api:
  build: .
  ports:
    - "8080:8080"

influxdb:
  image: influxdb:latest
  environment:
    - INFLUXDB_DB=sensors
  ports:
    - "8083:8083"
    - "8086:8086"

grafana:
  image: grafana/grafana:latest
  ports:
    - "5000:3000"
  links:
    - influxdb

telegraf:
  image: telegraf:latest
  links:
    - influxdb
    - api
  volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
