version: "3.7"

services:
  api:
    build: .
    expose:
      - 8080
    restart: always

  telegraf:
    image: telegraf:1.12.5
    networks:
      - default
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always

networks:
  influxdb:
    external:
      name: influxdb
